### ISSUE TITLE
Version upgrade

### ISSUE THREAD

**Issue by disorganised-mess** [shoulders/qwcrm#1668]
I've yet to figure out how to upgrade between releases. I'm currently on v3.0 and would like to get up to date on it. There doesn't seem to be a clear method of doing so. For all I know is I'm just not seeing something obvious, PBCK? I've referred back in the issues for something to go off of but can't find anything. I'm trying to avoid DB import/export where it is not necessary.
Thanks for the help.

**Comment by shoulders** [comment]
I will sort some simple instructions out tommorow for you, it is not difficult but if you dont know about it, it is sort of hidden.

I will do the proper documentation when I have release v3.2.0 because it will be getting a template upgrade to bootstrap.

p.s. what is 'PBCK' ?

**Comment by disorganised-mess** [comment]
Good deal, thanks. PBCK=Problem Between Chair and Keyboard.

**Comment by shoulders** [comment]
**Do this first**
- backup your database and files. You must do this for safety.
- (optional) try the upgrade on a copy of your QWcrm installation.
- (optional) check your Finance, Jobs, invoices for comparrisons later

**Instructions**
- delete all files from your QWcrm folder except for the configuration.php
- extract all of the files from the new QWcrm zip file into the same folder. This file structure will look like your previous version.
- access QWcrm as normal
- The upgrade notification will appear instead of your normal login screen
- Follow the upgrade prompts
- Done, QWcrm is now upgraded

**Notes**
- the configuration.php file will also be upgraded as needed
- You will need to re-upload your logo (this will be fixed in later versions)
- check to make sure that everything is as you expect. Finance, Jobs, invoices
- I have used this upgrade and everything on my setup is perfect but it does not harm to check. I do spend a lot of time checking the upgrade routines and comparing databases to make sure they work as expected.

**Comment by shoulders** [comment]
did you manage to upgrade your QWcrm?

**Comment by disorganised-mess** [comment]
I just saw the notice on you checking as I was coming to report in, lol. Yes. It worked without any issues from your side, had some on my server itself which were fairly easily resolved. I've documented everything I've gone through since using a RaspberryPi seems to create some issues, albeit minor, in configuration for the server itself. That said, it runs beautifully on an RPI2, my current setup. Thanks for the assistance. Things got busy and the upgrade had to take a back seat, sorry about that. If you'd like, either e-mail or a new issue here I can post the steps I've taken to get QWcrm installed and upgraded on the RPI. I will be opening some other issues once I can get my thoughts together on them, for your consideration, since there are some minor things regarding features and nuances.
Thanks again, best I can help is documentation. Like you I get busy with work, I do appreciate the time you've put into this and I do try and spread the word about it.

**Comment by shoulders** [comment]
@disorganised-mess 

If you open up a new issue here about the steps you have taken to install on a raspberry Pi that would be great. I would at some point I would like to put these sort of things on my website in the documentation.

**Comment by disorganised-mess** [comment]
Sounds good, I'll do that. It will take me a couple of days to get done though. Also, don't forget about the wiki feature here on GitHub as a potential secondary reference point for this sort of information. Of course, the RPI is just my platform and all the information should apply to any Debian based install though is likely generic enough that it won't matter which *nix distribution is being used.

**Comment by shoulders** [comment]
I will think about the github pages. But I will probably use quantumwarp.com becasue I will have some other software projects (not as big) and it is easier to look after in one place.

It is on the list. lol
