### ISSUE TITLE
ePrivacy GDPR

### ISSUE THREAD

**Issue by dirigit** [shoulders/qwcrm#1707]
Personal data have to be secured and kept private in any case!

There should be a cookie banner with Opt-**IN** functionality.

There should be nothing being an external tracker if it is not set by administrator and user getting information about it!

CDN (in case of usage) is also something to avoid like wrong binding to Facebook and the like.

**Comment by shoulders** [comment]
> Personal data have to be secured and kept private in any case!

Yes I agree. QWcrm does not offer encryption. The passwords are kept safe. After v3.2.0 I will look at all security and issues like this.

> There should be a cookie banner with Opt-IN functionality.

There does not need to be an `OPT In` to use QWcrm for normal business use because this is part of a legal contract between the company and the client (i.e. we are fixing their PC), implicit consent has been given. Tracking 'might' be allowed here without explicit consent because it is for normal busness use, I am not 100% on this one.

> There should be nothing being an external tracker if it is not set by administrator and user getting information about it!

This is related to the above. Currently there are no trackers in QWcrm. I had thought about an option to enable Google analytics but this would need to be turned on by an Admin

> CDN (in case of usage) is also something to avoid like wrong binding to Facebook and the like.

I will never use CDNs because then you could not use this system offline

**Comment by dirigit** [comment]
I agree with you in almost any case (eg for myself I don't use Google Analytics for braking privacy).

Only this implicit consent ... it's void when not written somewhere. Anything not being like an opt-in is void when it comes to electronic communication. Even using a vcard is only allowed when there is either consent is given or an absolut need to use it to fullfill the contract.

Maintenance of IT with "foreign" data needs a very special  contract (order processing) related to data protection. To be real save best choice is to make a movie whenever you touch a foreign PC and run a keylogger while working with keyboard and mouse ...

It took me some Euros and a lot of time to get a certificate in this relation but, I'm still no specialist.

**Comment by shoulders** [comment]
> absolut need to use it to fullfill the contract.

This is where QWcrm is placed. It is needed to fullfill the contract. This is the legal contract and when the client gets you to do a job, consent is given for their information to be used in fullfillment of the job. If it wasnt you could not invoice them.

> Only this implicit consent ... it's void when not written somewhere.

consent doesnt have to be written.  Conside this. When you have done the work you must do an invoice. This invoice will have the name and sometimes the address and this is a legal requirement. The customer does not have to give consent yet his information is recorded and stored. This is a requirement to fullfill the job.

p.s. I hate GDPR, there is a lot of mis-information out there.

thanks for the info. As I go, if you notice anything specific I can look into it for you.

**Comment by dirigit** [comment]
JFI, there is nothing implicit, contract data are another kind of animal:
http://curia.europa.eu/juris/document/document.jsf?text=&docid=218462&pageIndex=0&doclang=EN&mode=req&dir=&occ=first&part=1&cid=1438506
