### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by bangjuntak** [shoulders/qwcrm#1742]
i try install QWCRM 3.1.2 but i get error

![error install](https://user-images.githubusercontent.com/49651383/74684675-0fb12780-51ff-11ea-81d2-72c3af3e331b.png)
![error install 2](https://user-images.githubusercontent.com/49651383/74684832-82220780-51ff-11ea-9c04-788f367c00fc.png)
![error install3](https://user-images.githubusercontent.com/49651383/74684840-88b07f00-51ff-11ea-9443-5f6479759804.png)
![error install 4](https://user-images.githubusercontent.com/49651383/74684853-8c440600-51ff-11ea-9214-d2b74e05eab3.png)

FYI i don't know about programming  i just install this according tutorial.  please help me about this error

Regards

**Comment by shoulders** [comment]
- what server are you installing on?
- PHP and MySQL version number
- Windows or Linux
- I am assuming this failed when you submitted the administrator details.
- etc...

let me have a think. In a couple of days v3.1.2 is out.

**Comment by shoulders** [comment]
can you replicate the issue and tell me what you were doing?

thanks

**Comment by bangjuntak** [comment]
Hi Shoulders, thanks for your reply.

I have tried installing v3.1.2 several times, sometimes failed when submited company data and sometimes failed when submited administrator data.

This is my server detail
![Annotation 2020-02-18 113119](https://user-images.githubusercontent.com/49651383/74704430-ff22a080-5242-11ea-999d-bc4bcb93f813.png)

**Comment by shoulders** [comment]
hi

- What is your OS? What version of Ubuntu?
- How did you install the webserver on ubuntu? (I am a windows guy)
- I need to replicate your computer at my end to find out what is going on.

Can you tell me what the status of STRICT Mode is? A copy of the whole string might be useful
https://stackoverflow.com/questions/37964325/how-to-find-and-disable-mysql-strict-mode

Disabling STRICT mode is required becasue this causes issues with installation. It is on my list #1712 and this issue has some notes.

**Comment by dirigit** [comment]
Installation took place in home of admin. That's unusual.

Webserver isn't running as "admin". Can be a permission problem.

**Comment by shoulders** [comment]
@bangjuntak Did you get this fixed? If so what did you do?

I need to close this job so i can release the new version.

**Comment by dirigit** [comment]
Setup as is seen in description looks like running a (virtual) host in user's home directory without correct settings of permissions for such a setup. In case of user "admin" is user 0 switching Apache to run as "admin" should never work.

I suppose it's a permission problem because Ubuntu runs Apache as www-data AFAIK (I don't use this distribution for myself). It can be assigned to another username as well but, one should know what he is doing.

And: Even with Windows it's easy to cause such problems.

Recommendation for QWCRM is to check permissions READ and WRITE in case of need (cfg file). Changing permission of cfg files to RO is a security feature of many applications. When cfg is not writeable and application can not change permission in case of action needed - stop it. As long as READ is sufficient (no action) - go on.

**Comment by shoulders** [comment]
thanks @dirigit 

I will take that onboard. I am going to make the installer all AJAX which will help me see what is going on.
